spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ENC(pwAvrfwPnPlhX1wx4Uji5S1HPgjz840eul5KZxtAgi8coSXe4C3Wud2qGigjEfqFFxCtD8jm9ib6Nyj/ZvsiHArxj+UMicMoxjwcyaZ81Xs=)
    username: ENC(ayzyyRHZs+yyDXCMHijkNw==)
    password: ENC(Qhw0pcuK4dppToh93Me/Yw==)
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# logback location - log optimization
#logging:
#  config: classpath:logback/logback-default.xml
